on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH
      - name: moon version
        run: |
          moon version --all
          moonrun --version
      - name: moon check
        run: moon check
        # Temporarily disable this for backward API compatibility
        # run: moon check --deny-warn
      - name: moon info
        run: |
          moon info
          git diff --exit-code
      - name: moon test
        run: |
          moon test
          moon test --target js
      - name: format diff
        run: |
          moon fmt
          git diff --exit-code
      - name: publish
        run: |
          echo $SECRET > ~/.moon/credentials.json
          moon publish
          rm ~/.moon/credentials.json
        env:
          SECRET: ${{ secrets.MOONCAKES_MOONBITLANG_TOKEN }}